---
layout: post
title: Fresher's and Cambridge
date: '2009-10-05T23:04:00.000+01:00'
author: tim
tags: 
modified_time: '2009-11-08T03:04:10.205Z'
thumbnail: http://4.bp.blogspot.com/_hiNbF4SwSJU/SsopUVvyIzI/AAAAAAAAACo/66LFx8F1LaI/s72-c/HPIM1413.JPG
blogger_id: tag:blogger.com,1999:blog-8654393464763154.post-757675552769368757
blogger_orig_url: http://tburr.blogspot.com/2009/10/freshers-and-cambridge.html
---

The house is full, which is a good thing. It was awfully quiet w/ just Emilio and me here. The rest of my flatmates seem pretty cool. We went to the Forum to see <a href="http://www.youtube.com/watch?v=dnezldGu7JU">Wiley</a>* the other night, which was a lot of fun. Wiley wasn't actually that good live (he rapped a couple of songs on top of a tape of himself rapping, which was kind of like Michael Scott karaoke), but it was fun to go out and dance. <br /><br />There wasn't anything for foreign kids to do during the day, which didn't stop Jon from taking the piss out of me for being so lazy and skipping lectures. By about Wednesday, I was tired of this, and decided to go to Cambridge and see the sights. Good decision.<br /><a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://4.bp.blogspot.com/_hiNbF4SwSJU/SsopUVvyIzI/AAAAAAAAACo/66LFx8F1LaI/s1600-h/HPIM1413.JPG"><img style="float:left; margin:0 10px 10px 0;cursor:pointer; cursor:hand;width: 240px; height: 320px;" src="http://4.bp.blogspot.com/_hiNbF4SwSJU/SsopUVvyIzI/AAAAAAAAACo/66LFx8F1LaI/s320/HPIM1413.JPG" border="0" alt=""id="BLOGGER_PHOTO_ID_5389165333513904946" /></a><br />I visited Trinity College, and saw a piece of Babbage's <a href="http://en.wikipedia.org/wiki/Difference_engine">difference engine</a> at the Whipple History of Science Museum. I decided to visit the art museum on a whim. Among the things I saw: three Monets, four Picassos, a handful of Renoirs, three mummies, and a sweet old Italian painting of scenes from the Iliad. They also had some naturalist sketches drawn by Darwin and his contemporaries. Very cool.<br /><br />I caught the train back on Saturday. It was a lot of fun to organize a trip like that- taking care of train tickets and lodgings. I will definitely do something like that again. <br /><br />Back in Hatfield, I capped off the perfect weekend by watching OU destroy Miami on the internet. That's what happened- don't try to tell me otherwise. Jermaine Gresham and Ryan Broyles both had an outstanding game, and are perfectly healthy.   <br /><br />On a happier note, classes start Monday, and I finally think I've figured out where and when to be. <br /><br /><br /><br />*Don't actually watch the video; it is super-weird. I like the song ok, though.