---
layout: post
title: Spain, day three
date: '2009-11-16T21:58:00.005Z'
author: tim
tags: 
modified_time: '2009-11-17T00:08:18.965Z'
blogger_id: tag:blogger.com,1999:blog-8654393464763154.post-8065117242083777229
blogger_orig_url: http://tburr.blogspot.com/2009/11/spain-day-three.html
---

<a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://photos-a.ak.fbcdn.net/hphotos-ak-snc3/hs004.snc3/11139_194511271457_710286457_4067087_6941320_n.jpg"><img style="float:right; margin:0 0 10px 10px;cursor:pointer; cursor:hand;width: 302px; height: 201px;" src="http://photos-a.ak.fbcdn.net/hphotos-ak-snc3/hs004.snc3/11139_194511271457_710286457_4067087_6941320_n.jpg" border="0" alt="" /></a><br />Viernes y Sabado were both pretty sweet, but I think Domingo was my favorite of all. We started out at la Reina Sofia, which was very interesting. Guernica hit me in a way that modern art never has before. Pablo Picasso wants you to learn something from that painting.<br /><br /><a onblur="try {parent.deselectBloggerImageGracefully();} catch(e) {}" href="http://photos-f.ak.fbcdn.net/hphotos-ak-snc3/hs024.snc3/11139_194511396457_710286457_4067104_6780179_n.jpg"><img style="float:left; margin:0 10px 10px 0;cursor:pointer; cursor:hand;width: 302px; height: 201px;" src="http://photos-f.ak.fbcdn.net/hphotos-ak-snc3/hs024.snc3/11139_194511396457_710286457_4067104_6780179_n.jpg" border="0" alt="" /></a>After that, we explored el Parque del Buen Retiro, which was really amazing. We wandered around for hours, constantly stumbling upon a cool statue or an interesting tree. We took a boat out on the little lake in front of the statue of King Alfonso XII, and we saw el Palacio de Cristal, which was gorgeous. Katie says that Retiro is her favorite place in Madrid, and I can see why. The northeast corner of the park is marked by la Puerta de Alcala, which points toward la Puerta de Madrid, which we saw on Friday.<br /><br />Our last stop of the day was el Prado. We decided to pay 4€ apiece to skip the line of people waiting for free admission, which probably saved us an hour. This was a good decision, since we just barely saw everything we wanted before the museum closed. Katie showed me the most famous painting in Spain: "Las Meninas." She told me all about Velazquez, Goya, El Greco y Murillo. I also learned a lot about the various kings that they worked for. We saw Goya's Black Paintings, which were really cool, in a creepy kind of way. I showed her Bosch's "Garden of Earthly Delights," that being the painting in the building that I know anything about.<br /><br />Spanish food of the day: Churros are little fried pastry things, kind of like something you would get at a state fair. Dip them in hot chocolate, but this is more like fondue than Swiss Miss. Yum... <br />We got beef empanadas to eat in the park. These were basically thin meat pies. Not bad, but I think the British do better meat pies.<br />Finally, Tostas are like a cross between bocadillos and pizza. You get sandwich toppings on a piece of toast, rather than in a baguette-y thing. Also very tasty.